name = "Thinkers"
uuid = "6d80a3f9-a943-41fa-97b3-3004c0daf7a3"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "0.2.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
